---
title: '`r params$report_title`'
author: '河南省'
date: '`r Sys.Date()`'
params:
  report_data: null
  report_title: "default title"
  year: 2021
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: 3
    theme: united
  word_document:
    toc: FALSE
    toc_depth: 3
    number_sections: true
    fig_width: 6
    fig_height: 4
    fig_caption: true
    highlight: pygments
    reference_docx: chinese-article.docx
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, fig.height = 8,
                      fig.width = 8, fig.align = "center")
pkgs <- c("canregtools", "dplyr", "tidyr", "showtext", "epoxy", "ggplot2",
          "forcats")
mess <- lapply(pkgs, library, character.only = TRUE)
showtext_auto()
source("functions.R")
std <- quality |> filter(year == 2017)
```

```{r}
data <- params$report_data
data <- cr_select(data, !rks == 0)
data2 <- cr_reframe(data, strat = "city")
fbsw <- count_canreg(data2)
quality <- create_quality(fbsw, year)
```

## 各地市`r params$year`年肿瘤登记数据质量控制指标

```{r}
quality |>
  add_labels(label_type = "abbr") |>
  filter(year == params$year) |>
  select(-cancer, -sex, -site, -icd10, -year, -areacode) |>
  mutate(id = row_number()) |>
  select(id, everything()) |>
  kableExtra::kable()
```



