#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr as_tibble
#' @importFrom dplyr mutate
#' @importFrom dplyr bind_rows
#' @importFrom dplyr group_by
#' @importFrom dplyr reframe
#' @importFrom dplyr across
#' @importFrom dplyr c_across
#' @importFrom dplyr all_of
#' @importFrom dplyr any_of
#' @importFrom dplyr contains
#' @importFrom dplyr where
#' @importFrom dplyr everything
#' @importFrom dplyr left_join
#' @importFrom dplyr full_join
#' @importFrom dplyr select
#' @importFrom dplyr row_number
#' @importFrom dplyr count
#' @importFrom dplyr pull
#' @importFrom dplyr starts_with
#' @importFrom dplyr rowwise
#' @importFrom dplyr arrange
#' @importFrom dplyr desc
#' @importFrom dplyr tibble
#' @importFrom dplyr filter
#' @importFrom dplyr join_by
#' @importFrom dplyr cur_column
#' @importFrom dplyr summarise
#' @importFrom dplyr slice_tail
#' @importFrom dplyr group_split
#' @importFrom dplyr rename
#' @importFrom dplyr bind_cols
#' @importFrom dplyr ungroup
#' @importFrom dplyr dense_rank
#' @importFrom graphics legend par points
#' @importFrom graphics lines
#' @importFrom graphics mtext
#' @importFrom graphics rect
#' @importFrom graphics segments
#' @importFrom graphics text
#' @importFrom graphics title
#' @importFrom grDevices hcl.colors
#' @importFrom grDevices palette
#' @importFrom purrr compact
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_dfr
#' @importFrom purrr pluck
#' @importFrom purrr reduce
#' @importFrom readxl read_excel
#' @importFrom rlang :=
#' @importFrom rlang enquo
#' @importFrom rlang enquos
#' @importFrom rlang as_name
#' @importFrom rlang quo_is_null
#' @importFrom rlang sym
#' @importFrom rlang syms
#' @importFrom stats na.omit
#' @importFrom stats qgamma
#' @importFrom stats qnorm
#' @importFrom stats setNames
#' @importFrom tidyr expand_grid
#' @importFrom tidyr pivot_wider
## usethis namespace: end
NULL
