#' Count cancer incident cases and deaths in each year, sex, cancer sites
#' and generate a data frame.
#'
#' @param fb A data frame that generated by prep_regdata function.
#' @param sw A data frame that generated by prep_regdata function.
#' @param pop A data frame that generated by prep_regdata function.
#' @param year Variable name for year.
#' @param sex Variable name for gender.
#' @param agegrp Variable name for age categories.
#' @param icd_cat Variable name for cancer categories.
#' @param basi Variable name for diagnostic basi for cancer cases.
#'
#' @return A data frame that contain the counts of cancer cases and deaths.
#' @export
#'
#' @import dplyr
#' @importFrom purrr reduce
#' @import readxl
#'
#' @examples
#' library(canregtools)
#' library(readxl)
#' file <- system.file("extdata", "411721.xls", package = "canregtools")
#' FB <- read_excel(file, sheet="FB")
#' SW <- read_excel(file, sheet="SW")
#' POP <- read_excel(file, sheet="POP")
#' fb <- prep_regdata(FB, icd_type = "big")
#' sw <- prep_regdata(SW, icd_type = "big")
#' pop <- prep_regdata(POP)
#' fbsw <- fbswicd(fb, sw, pop)
fbswicd <- function(fb,
                    sw,
                    pop,
                    year = year,
                    sex = sex,
                    agegrp = agegrp,
                    icd_cat = icd_cat,
                    basi = basi) {
  # 构建分年份、性别、年龄组的计数函数
  reg_count <- function(data, varname = "fbs") {
      bind_rows(
        data %>%
          count(year, sex, agegrp, icd_cat, name = varname, .drop = FALSE),
        data %>%
          count(year, sex, agegrp, name = varname, .drop = FALSE) %>%
          mutate(icd_cat = "\u5408\u8ba1", icd_cat = as.factor(icd_cat))
      )
    }

  #统计发病数、死亡数、病理诊断数和dco数.
  res <- list(
    reg_count(fb, varname = "fbs"),
    reg_count(sw, varname = "sws"),
    fb %>% filter(basi %in% c(5, 6, 7)) %>% reg_count(varname = "mv"),
    fb %>% filter(basi == 0) %>% reg_count(varname = "dco")) %>%
    purrr::reduce(left_join, by = c("year", "sex", "agegrp", "icd_cat")) %>%
    left_join(pop, by = c("year", "sex", "agegrp")) %>%
    arrange(year, sex, icd_cat, agegrp)
  return(res)
}
